[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200